spring:
  main:
    banner-mode: console
  shell:
    history:
      enabled: false
  datasource:
    url: jdbc:h2:mem:maindb
    driverClassName: org.h2.Driver
  #  datasource:
  #    url: ${DB_URL}
  #    username: ${DB_USER}
  #    password: ${DB_PASSWORD}
  #    driverClassName: org.postgresql.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: none

    properties:
      hibernate:
        format_sql: true
    show-sql: true

  liquibase:
    change-log: classpath:db/changelog/changelog.xml
    contexts: dev

logging:
  level:
    root: info