spring:
  main:
    banner-mode: console
  data:
    mongodb:
      host: localhost
      port: 27017
      database: library
      username: root
      password: password
      authentication-database: admin

server:
  port: 8080

logging:
  level:
    root: info
