spring:
  main:
    banner-mode: console
  shell:
    history:
      enabled: false
  datasource:
    url: jdbc:h2:mem:maindb
#    user: sa
#    password: 1
    driverClassName: org.h2.Driver

  liquibase:
    change-log: classpath:db/changelog/changelog.xml
    contexts: dev

logging:
  level:
    root: info