name: Build

on:
  pull_request:

jobs:
  build-app:
    runs-on: ubuntu-latest
    services:
      mongo:
        image: mongo:latest
        ports:
          - 27017:27017

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Wait for MongoDB to be ready
        run: |
          for i in {1..30}; do
            if nc -z localhost 27017; then
              echo "MongoDB is up and running!"
              exit 0
            fi
            echo "Waiting for MongoDB to start..."
            sleep 5
          done
          echo "MongoDB did not start in time"
          exit 1

      - name: Build application
        run: |
          mvn verify -Dspring.data.mongodb.uri=mongodb://localhost:27017/testdb --no-transfer-progress
